// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/AboutUs/AboutUsOne.tsx";
import * as $$$$$$1 from "./sections/AboutUs/AboutUsThree.tsx";
import * as $$$$$$2 from "./sections/AboutUs/AboutUsTwo.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$5 from "./sections/Content/Benefits.tsx";
import * as $$$$$$6 from "./sections/Content/ContentOne.tsx";
import * as $$$$$$7 from "./sections/Content/ContentThree.tsx";
import * as $$$$$$8 from "./sections/Content/ContentTwo.tsx";
import * as $$$$$$9 from "./sections/Content/Faq.tsx";
import * as $$$$$$10 from "./sections/Content/Logos.tsx";
import * as $$$$$$11 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$12 from "./sections/Cta/Cta.tsx";
import * as $$$$$$13 from "./sections/Development/ContactForm.tsx";
import * as $$$$$$14 from "./sections/Development/Differences2.tsx";
import * as $$$$$$15 from "./sections/Development/Fitas2.tsx";
import * as $$$$$$16 from "./sections/Development/Footer.tsx";
import * as $$$$$$17 from "./sections/Development/Header.tsx";
import * as $$$$$$18 from "./sections/Development/Hero2.tsx";
import * as $$$$$$19 from "./sections/Development/Newsletter.tsx";
import * as $$$$$$20 from "./sections/Development/Partnership.tsx";
import * as $$$$$$21 from "./sections/Development/Presentation2.tsx";
import * as $$$$$$22 from "./sections/Development/Services2.tsx";
import * as $$$$$$23 from "./sections/Development/Testimonials.tsx";
import * as $$$$$$24 from "./sections/example1.tsx";
import * as $$$$$$25 from "./sections/Footer/Footer.tsx";
import * as $$$$$$26 from "./sections/Gallery.tsx";
import * as $$$$$$27 from "./sections/Header/Header.tsx";
import * as $$$$$$28 from "./sections/Hero/Hero.tsx";
import * as $$$$$$29 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$30 from "./sections/Images/Carousel.tsx";
import * as $$$$$$31 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$32 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$33 from "./sections/Layout/Container.tsx";
import * as $$$$$$34 from "./sections/Layout/Flex.tsx";
import * as $$$$$$35 from "./sections/Layout/Grid.tsx";
import * as $$$$$$36 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$37 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$38 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$39 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$40 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$41 from "./sections/Newsletter.tsx";
import * as $$$$$$42 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$43 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$44 from "./sections/Product/NotFound.tsx";
import * as $$$$$$45 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$46 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$47 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$48 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$49 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$50 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$51 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$52 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$53 from "./sections/Theme/Theme.tsx";
import * as $$$$$$54 from "./sections/Theme/ThemeAutumn.tsx";
import * as $$$$$$55 from "./sections/Theme/ThemeFall.tsx";
import * as $$$$$$56 from "./sections/Theme/ThemeNight.tsx";
import * as $$$$$$57 from "./sections/Theme/ThemeSummer.tsx";
import * as $$$$$$58 from "./sections/Theme/ThemeWinter.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/hackathon4time5/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/hackathon4time5/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/hackathon4time5/sections/AboutUs/AboutUsOne.tsx": $$$$$$0,
    "deco-sites/hackathon4time5/sections/AboutUs/AboutUsThree.tsx": $$$$$$1,
    "deco-sites/hackathon4time5/sections/AboutUs/AboutUsTwo.tsx": $$$$$$2,
    "deco-sites/hackathon4time5/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "deco-sites/hackathon4time5/sections/Category/CategoryList.tsx": $$$$$$4,
    "deco-sites/hackathon4time5/sections/Content/Benefits.tsx": $$$$$$5,
    "deco-sites/hackathon4time5/sections/Content/ContentOne.tsx": $$$$$$6,
    "deco-sites/hackathon4time5/sections/Content/ContentThree.tsx": $$$$$$7,
    "deco-sites/hackathon4time5/sections/Content/ContentTwo.tsx": $$$$$$8,
    "deco-sites/hackathon4time5/sections/Content/Faq.tsx": $$$$$$9,
    "deco-sites/hackathon4time5/sections/Content/Logos.tsx": $$$$$$10,
    "deco-sites/hackathon4time5/sections/Content/Testimonials.tsx": $$$$$$11,
    "deco-sites/hackathon4time5/sections/Cta/Cta.tsx": $$$$$$12,
    "deco-sites/hackathon4time5/sections/Development/ContactForm.tsx": $$$$$$13,
    "deco-sites/hackathon4time5/sections/Development/Differences2.tsx":
      $$$$$$14,
    "deco-sites/hackathon4time5/sections/Development/Fitas2.tsx": $$$$$$15,
    "deco-sites/hackathon4time5/sections/Development/Footer.tsx": $$$$$$16,
    "deco-sites/hackathon4time5/sections/Development/Header.tsx": $$$$$$17,
    "deco-sites/hackathon4time5/sections/Development/Hero2.tsx": $$$$$$18,
    "deco-sites/hackathon4time5/sections/Development/Newsletter.tsx": $$$$$$19,
    "deco-sites/hackathon4time5/sections/Development/Partnership.tsx": $$$$$$20,
    "deco-sites/hackathon4time5/sections/Development/Presentation2.tsx":
      $$$$$$21,
    "deco-sites/hackathon4time5/sections/Development/Services2.tsx": $$$$$$22,
    "deco-sites/hackathon4time5/sections/Development/Testimonials.tsx":
      $$$$$$23,
    "deco-sites/hackathon4time5/sections/example1.tsx": $$$$$$24,
    "deco-sites/hackathon4time5/sections/Footer/Footer.tsx": $$$$$$25,
    "deco-sites/hackathon4time5/sections/Gallery.tsx": $$$$$$26,
    "deco-sites/hackathon4time5/sections/Header/Header.tsx": $$$$$$27,
    "deco-sites/hackathon4time5/sections/Hero/Hero.tsx": $$$$$$28,
    "deco-sites/hackathon4time5/sections/Images/BannerGrid.tsx": $$$$$$29,
    "deco-sites/hackathon4time5/sections/Images/Carousel.tsx": $$$$$$30,
    "deco-sites/hackathon4time5/sections/Images/ImageGallery.tsx": $$$$$$31,
    "deco-sites/hackathon4time5/sections/Images/ShoppableBanner.tsx": $$$$$$32,
    "deco-sites/hackathon4time5/sections/Layout/Container.tsx": $$$$$$33,
    "deco-sites/hackathon4time5/sections/Layout/Flex.tsx": $$$$$$34,
    "deco-sites/hackathon4time5/sections/Layout/Grid.tsx": $$$$$$35,
    "deco-sites/hackathon4time5/sections/Layout/GridItem.tsx": $$$$$$36,
    "deco-sites/hackathon4time5/sections/Links/LinkTree.tsx": $$$$$$37,
    "deco-sites/hackathon4time5/sections/Links/Shortcuts.tsx": $$$$$$38,
    "deco-sites/hackathon4time5/sections/Miscellaneous/CampaignTimer.tsx":
      $$$$$$39,
    "deco-sites/hackathon4time5/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$40,
    "deco-sites/hackathon4time5/sections/Newsletter.tsx": $$$$$$41,
    "deco-sites/hackathon4time5/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$42,
    "deco-sites/hackathon4time5/sections/Product/ImageGallerySlider.tsx":
      $$$$$$43,
    "deco-sites/hackathon4time5/sections/Product/NotFound.tsx": $$$$$$44,
    "deco-sites/hackathon4time5/sections/Product/NotFoundChallenge.tsx":
      $$$$$$45,
    "deco-sites/hackathon4time5/sections/Product/ProductInfo.tsx": $$$$$$46,
    "deco-sites/hackathon4time5/sections/Product/ProductShelf.tsx": $$$$$$47,
    "deco-sites/hackathon4time5/sections/Product/ProductShelfTabbed.tsx":
      $$$$$$48,
    "deco-sites/hackathon4time5/sections/Product/SearchResult.tsx": $$$$$$49,
    "deco-sites/hackathon4time5/sections/Product/Wishlist.tsx": $$$$$$50,
    "deco-sites/hackathon4time5/sections/Social/InstagramPosts.tsx": $$$$$$51,
    "deco-sites/hackathon4time5/sections/Social/WhatsApp.tsx": $$$$$$52,
    "deco-sites/hackathon4time5/sections/Theme/Theme.tsx": $$$$$$53,
    "deco-sites/hackathon4time5/sections/Theme/ThemeAutumn.tsx": $$$$$$54,
    "deco-sites/hackathon4time5/sections/Theme/ThemeFall.tsx": $$$$$$55,
    "deco-sites/hackathon4time5/sections/Theme/ThemeNight.tsx": $$$$$$56,
    "deco-sites/hackathon4time5/sections/Theme/ThemeSummer.tsx": $$$$$$57,
    "deco-sites/hackathon4time5/sections/Theme/ThemeWinter.tsx": $$$$$$58,
  },
  "apps": {
    "deco-sites/hackathon4time5/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/hackathon4time5/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/hackathon4time5",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
